#!/usr/bin/env ruby

Dir.chdir("ext/libxml") do
  unless file?('Makefile')
    sh "ruby extconf.rb"
  end

  unless ARGV[0] == 'setup'
    sh "make #{ARGV.join(' ')}"
  end
end


# Eric Hodel said NOT do this.
#
#cp "ext/xml/*.#{dlext}", "lib/xml/#{arch}/"
#
#
#def dlext
#  Config::CONFIG['DLEXT']
#end
#
#def arch
#  Config::CONFIG['arch']
#end

