#!/usr/bin/env ruby

# TODO: Ensure compile first (but only if needed)
#
# sh "task/compile"

# Run unit tests

live = ARGV.include?('--live')

unless live
  $LOAD_PATH.unshift(File.expand_path('ext/libxslt'))
end

if find = ARGV.select{ |a| a !~ /^[-]/ }[0]
  find = File.join(find, '**', '*.rb') unless file?(find)
else
  find = 'tests/**/*.rb'
end

Dir.glob(find).each do |file|
  next if dir?(file)
  begin
    puts "Loading: #{file}" if $DEBUG
    load(file)
  rescue LoadError
    puts "Error loading: #{file}"
  end
end


