# This is for backwards compatibility and is DEPRECATED
module LibXML
  class Tree 
    # :enddoc: 
    ELEMENT_NODE = Node::XML_ELEMENT_NODE
    ATTRIBUTE_NODE = Node::XML_ATTRIBUTE_NODE
    TEXT_NODE = Node::XML_TEXT_NODE
    CDATA_SECTION_NODE = Node::XML_CDATA_SECTION_NODE
    ENTITY_REF_NODE = Node::XML_ENTITY_REF_NODE
    ENTITY_NODE = Node::XML_ENTITY_NODE
    PI_NODE = Node::XML_PI_NODE
    COMMENT_NODE = Node::XML_COMMENT_NODE
    DOCUMENT_NODE = Node::XML_DOCUMENT_NODE
    DOCUMENT_TYPE_NODE = Node::XML_DOCUMENT_TYPE_NODE
    DOCUMENT_FRAG_NODE = Node::XML_DOCUMENT_FRAG_NODE
    NOTATION_NODE = Node::XML_NOTATION_NODE
    HTML_DOCUMENT_NODE = Node::XML_HTML_DOCUMENT_NODE
    DTD_NODE = Node::XML_DTD_NODE
    ELEMENT_DECL = Node::XML_ELEMENT_DECL
    ATTRIBUTE_DECL = Node::XML_ATTRIBUTE_DECL
    ENTITY_DECL = Node::XML_ENTITY_DECL
    NAMESPACE_DECL = Node::XML_NAMESPACE_DECL
    XINCLUDE_START = Node::XML_XINCLUDE_START
    XINCLUDE_END = Node::XML_XINCLUDE_END
    DOCB_DOCUMENT_NODE = Node::XML_DOCB_DOCUMENT_NODE
  end  
end
