#!/usr/bin/env ruby

# TODO: Ensure compile first (but only if needed)
# system "task/make"

# Run memory tests

live = ARGV.include?('--live')

unless live
  $LOAD_PATH.unshift(File.expand_path('ext/libxml'))
  $LOAD_PATH.unshift(File.expand_path('lib'))
end
$LOAD_PATH.unshift('test')  # NEEDED?

unless glob = ARGV.select{ |a| a !~ /^[-]/ }[0]
  glob = 'test/ets_*.rb'
end

Dir[glob].each do |fn|
  next if File.directory?(fn)
  puts "test #{fn}"
  f=Process.fork
  if f.nil?
    require fn
    exit
  end
  rss_k=0
  while (px=Process.wait2(f,Process::WNOHANG)).nil?
    sleep 2
    rss_k2=`ps -o rss= -p #{f}`.to_i
    rss_k=(rss_k2>rss_k) ? rss_k2 : rss_k
  end
  pid,status=px
  puts "\nProcess #{pid} exited status #{status.exitstatus}, max rss(k) #{rss_k}"
end

