name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}${{ matrix.yjit }}
    env:
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: libxml2-dev
          # brew: libxml2
          mingw: libxml2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        timeout-minutes: 10
      - name: Build
        run: bundle exec rake compile
      - name: Test
        run: bundle exec rake test
